{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sigmajs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sigmajs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sigmajs/sigmajs_{{ version }}.tar.gz
  sha256: 6587ca1579996371dc522f2962c91877aa8f10877e3d9ed13ac848fb2ea546b4

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-crosstalk
    - r-dplyr >=0.7.0
    - r-htmltools
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-shiny
    - r-scales
  run:
    - r-base
    - r-crosstalk
    - r-dplyr >=0.7.0
    - r-htmltools
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-shiny
    - r-scales

test:
  commands:
    - $R -e "library('sigmajs')"           # [not win]
    - "\"%R%\" -e \"library('sigmajs')\""  # [win]

about:
  home: http://sigmajs.john-coene.com/
  license: MIT
  summary: Interface to 'sigma.js' graph visualization library including animations, plugins
    and shiny proxies.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: sigmajs
# Title: Interface to 'Sigma.js' Graph Visualization Library
# Date: 2018-11-18
# Version: 0.1.2
# Authors@R: person("John", "Coene", email = "jcoenep@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6637-4107"))
# Description: Interface to 'sigma.js' graph visualization library including animations, plugins and shiny proxies.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# URL: http://sigmajs.john-coene.com/
# BugReports: https://github.com/JohnCoene/sigmajs/issues
# Imports: htmlwidgets, dplyr, magrittr, shiny, jsonlite, igraph, htmltools, purrr, crosstalk
# Suggests: knitr, rmarkdown, DT, testthat, covr
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-11-18 17:22:07 UTC; jp
# Author: John Coene [aut, cre] (<https://orcid.org/0000-0002-6637-4107>)
# Maintainer: John Coene <jcoenep@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-11-18 17:40:02 UTC
